name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Get dependencies
      run: go get

    - name: GolangCI-Lint
      run:  curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v1.21.0 && golangci-lint run --enable=golint --disable=deadcode,unused ./...

    - name: Test
      run: go test ./...
      
    - name: Benchmark
      run: go test -benchmem -bench .

    - name: Build
      run: go build -v .
